export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const ACTIVE_STATE = "ACTIVE_STATE";
export const ACTIVE_SETTING_STATE = "ACTIVE_SETTING_STATE";

export const STAFF_LOGIN = "STAFF_LOGIN";
export const UPDATE_STAFF_LOGIN = "UPDATE_STAFF_LOGIN";
export const ACTIVE_SETTINGS_TAB = "ACTIVE_SETTINGS_TAB";
export const SHOW_SIDEBAR="SHOW_SIDEBAR"