export const defaultMaterials = [
    {
        "id": 4,
        "name": "Hi index 1.70 & above",
        "sphere_from": null,
        "sphere_to": null,
        "cylinder_from": null,
        "cylinder_to": null,
    },
    {
        "id": 5,
        "name": "Hi index 1.67",
        "sphere_from": null,
        "sphere_to": null,
        "cylinder_from": null,
        "cylinder_to": null,
    },
    {
        "id": 6,
        "name": "Hi index 1.60",
        "sphere_from": null,
        "sphere_to": null,
        "cylinder_from": null,
        "cylinder_to": null,
    }, {
        "id": 3,
        "name": "Trivex",
        "sphere_from": null,
        "sphere_to": null,
        "cylinder_from": null,
        "cylinder_to": null,
    },
    {
        "id": 2,
        "name": "Polycarbonate",
        "sphere_from": null,
        "sphere_to": null,
        "cylinder_from": null,
        "cylinder_to": null,
    },
    {
        "id": 1,
        "name": "CR39",
        "sphere_from": null,
        "sphere_to": null,
        "cylinder_from": null,
        "cylinder_to": null,
    },

]